### ISSUE TITLE
[Feature Request] SFP/Phylink support

### ISSUE THREAD

**Issue by robimarko** [Marvell-switching/Switchdev-prestera#10]
**Is your feature request related to a problem? Please describe.**
Currently, the mainline Prestera driver does not support SFP-s/Phylink.

This means, that it's not possible to attach SFP buses to the switch port so that kernel could identify them and utilize Phylink to
change the PHY mode for example from 10GBase-R to 1000Base-X but rather it's up to the user to do so manually in order for the
modules to work.

This also means that there is no ethtool integration to use the standard `ethtool -m` op to query information about the module attached to the individual switch ports.

This is less of an issue on copper-focused switches that have 5 SFP+ ports but on SFP+ only switches it's a big inconvenience.

**Does the LK already supports this feature**
Linux kernel already provides the means to automate SFP identification and port configuration via the SFP bus and Phylink.
Ethtool as well already has support for querying and/or setting various SFP module parameters.

**Describe the solution you'd like**
Phylink support added to the mainline driver so that SFP buses can be attached via DTS to individual switch ports.

**Additional context**
This feature is already present in the DENT version of the driver and is proven to work.
It would significantly improve the customer experience.

**Comment by Mickey201** [comment]
Hi Robert, 
We are not sure we align with your comment. The phylink driver is included on all the current supported platforms as part of the platform drivers, the config files, the DTS files, and the CPLD-GPIO drivers.
The required support on the Switchdev driver was already included a year ago and till now works as expected.
Please check your platform drivers and your DTS configuration.
Notice, the SFP has several signals that require GPIO signals support.
Regards, Mickey.

**Comment by robimarko** [comment]
Hi Mickey,

I was referring to the upstream/mainline driver, it has no Phylink/SFP support while the DENT one has.
We are exposing the individual SFP buses like on other platforms, but there is currently no support for actually attaching them to the switch ports like you can do in the DENT version, that's the issue.

**Comment by Mickey201** [comment]
Ok, now I get it. We are doing a continuous effort to upstream all our drivers but as you know it takes time and a lot of effort.
Yet, I don't think this is an enhancement request as the feature already exists in the DENT drivers.
BTW. as the code is already accessible in the DENT - we will appreciate also your assistance with upstreaming the code :-) if there's time pressure - I'm sure you can do a great job.
We will check about the upstream plans and update you.

**Comment by Mickey201** [comment]
Hi Robert,
This feature is in our upstream backlog although currently, I can't commit on a specific date.
Anyway, I think you guys also can handle it if you find it urgent.
I'm currently closing this issue as the feature is already supported.
Regards, Mickey.

**Comment by jmpolom** [comment]
I request that this issue be re-opened until support is mainlined. It would be nice to track features that are not yet mainlined so users can assess whether the DENT or mainline driver is an appropriate choice.

**Comment by Mickey201** [comment]
The intention of this issue list is to report is about real Switchdev issues or new feature requests.

**Comment by jmpolom** [comment]
If you do not want to have open issues on this tracker for features yet to be upstreamed, can that information be posted elsewhere? As a user I would like to know the current states of both the driver in mainline and in DENT. I would rather not have to just try the mainline driver to figure out what it does or doesn't do. That is a poor user experience.

**Comment by Mickey201** [comment]
Please refer to this link:
https://github.com/Marvell-switching/switchdev-prestera

**Comment by lperkov** [comment]
Can this issue please be reopened for better tracking? It is documented on homepage that the feature exists in 3.1.1. driver within DentOS but there are customers who would like to have this supported in mainline Linux driver.

**Comment by Mickey201** [comment]
Luka, As I replied above, Marvell's intention is to commit these changes into mainline and this specific feature was already in the tasks backlog... yet, as you know the current geo-environment is a bit challenging and we have constant plans updated from time to time. 
And above all, the code was committed to the dentos REPO and you guys are a very talented ENG - feel free to make the required modification and upstream it.
