### ISSUE TITLE
Implement the BR_LOCKED flag for 802.1x

### ISSUE THREAD

**Issue by lperkov** [Marvell-switching/Switchdev-prestera#12]
**Is your feature request related to a problem? Please describe.**
Currently, the 802.1x support is dependent on using TC filter rules for filtering the ingress traffic, however, since the Prestera driver has no egress qdisc support there is no egress filtering.

This is an issue since 802.1x requires filtering the traffic and only allowing EAP/EAPOL packets until the client is authenticated.

**Does the LK already supports this feature**
Upstream Linux has recently received support for locked bridge ports, this is directly aimed at 802.1x support.
It is a way to do SA filtering that is specifically switchdev offloadable for maximum performance.
Setting a bridge port in locked mode means that only authenticated MAC addresses are allowed to have traffic
forwarded.

iproute2 already has support for utilizing the port locking feature, and there are Hostapd patches to handle authenticating the clients and populating the static FDB entries for them.

**Describe the solution you'd like**
For the Prestera driver to implement the `BR_LOCKED` flag.

cc @jmpolom @robimarko

**Comment by Mickey201** [comment]
Luka, your enhancement request is appreciated. 
We will examine the expected functional behavior, the potential business, the dentos REPO readiness, and then decide on the priority.
Did you check on which LK version it was first introduced?
We are also patiently waiting to see the 802.1X implementation you succeed to introduced. Do you have a target date for sharing it with our precious community?

**Comment by robimarko** [comment]
It was introduced in 5.18

**Comment by Mickey201** [comment]
Thank Robert, well - this might be a problem. We currently focusing LK 5.15 and I don't think we need to do Kernel features back-porting. I created a new label to track this enhancement in the future,

**Comment by jmpolom** [comment]
I think this is at least a semi-blocking issue to providing full and complete 802.1x support with MAB or simple port security on the respective Prestera platforms. This is a feature common on many low end managed switch platforms so it should be fully supported as soon as possible.

@Mickey201 given that this feature was added in more recently than 5.15, is it possible to focus on a newer kernel release so this feature could be prioritized?

**Comment by Mickey201** [comment]
The DENT community focus is on a long-term release (e.g. 5.10 or 5.15) and as a member of this community, we are following this approach. Once the next long-term will be declared we will back to this topic.

**Comment by jmpolom** [comment]
@Mickey201 would it be possible for FDB locking targeting a kernel >5.15 be worked on a parallel path? I would hope that the dentOS release moves to whatever the next LTS is at the end of 2022, so there will be some advancement here no matter what.

I think it would be nice to find some middle ground here. I feel like the approach above is just justifying a reason to do nothing. Clearly there's obvious indication 802.1x is important for growing deployment numbers of this hardware. The approach you mentioned doesn't meet the needs of the current community or prospective community.

**Comment by Mickey201** [comment]
We added this feature to the Marvell Switchdev driver road map.
It is targeted to be delivered as part of the DENT 3.0 release.

**Comment by Mickey201** [comment]
Implementation done, will be included on DENT 3.0.
Target release: EO Q4-22

**Comment by lperkov** [comment]
Hello @Mickey201,

Do you have any plans relating to upstreaming this feature within the Linux kernel?

Thanks,

Luka

**Comment by Mickey201** [comment]
Hi Luka, the general idea is to upstream all the Prestera Switchdev Drivers depending on availability and priorities.
Currently, there is no target date for this support to be upstreamed.
Anyway, the Switchdev driver support will be provided soon to the DENT GitHub.
Best Regards, Mickey.
