### ISSUE TITLE
[Documentation] - Typos in L3 configuration

### ISSUE THREAD

**Issue by ksandeep-palc** [Marvell-switching/Switchdev-prestera#14]
**Describe the bug**
https://github.com/Marvell-switching/switchdev-prestera/wiki/static-route

Typos needs to be corrected in below example - Also a request to change the wiki page title from "Static route" to "L3 configurations"

.1Q Bridge Example:
ip link add name br1 type bridge vlan filtering 1
ip link set sw1p4 master br0
ip link set sw1p4 up
bridge vlan add vid 10 dev sw1p14 untagged pvid
ip link add link br0 name br0.10 type vlan id 10
bridge vlan add dev br0 vid 10 self
ip addr add 192.1684.1/24 dev br0.10

**Expected behavior**
ip link add name br0 type bridge vlan_filtering 1
ip link set sw1p4 master br0
ip link set sw1p4 up
bridge vlan add vid 10 dev sw1p4 untagged pvid
ip link add link br0 name br0.10 type vlan id 10
bridge vlan add dev br0 vid 10 self
ip addr add 192.168.4.1/24 dev br0.10

**Comment by Mickey201** [comment]
Hi Sandeep, thanks for your comments.
These changes will be considered as part of the follow-up WIKI updated.
BR, Mickey

**Comment by taraschornyiplv** [comment]
wiki updated
