### ISSUE TITLE
802.1q support

### ISSUE THREAD

**Issue by jmpolom** [Marvell-switching/Switchdev-prestera#6]
What are the limitations of 802.1q support in the latest iteration of the Prestera switchdev driver? The wiki seems to be over a year old so I suspect some things have changed in the mean time.

Does this driver support creating VLAN sub-devices that can have addresses assigned to them? This would probably fall under the "VLAN unaware" bridge configuration category which is pretty sparse in the wiki.

Some improved documentation is needed here that identifies supported features and current limitations.

**Comment by Mickey201** [comment]
The wiki pages are in the update process. 
As for the VLAN interface support:
Setting IP on VLAN sub-interface on top of .1Q bridge
$ ip link add name br1 type bridge vlan filtering 1
$ ip link set sw1p4 master br0
$ ip link set sw1p4 up
$ ip link add link br0 name br0.10 type vlan id 10
$ bridge vlan add dev br0 vid 10 self
$ ip addr add 192.1684.1/24 dev br0.10

**Comment by jmpolom** [comment]
Some additional questions concerning current limitations:
 1. Is setting an address on a VLAN netdev unsupported currently? I don’t see this limitation specifically enumerated in the wiki however it is also not specifically shown. This could be useful on a VLAN unaware bridge:
```
$ ip link add link sw1p4 name sw1p4.50 type vlan id 30
$ ip link add link sw1p4 name sw1p4.60 type vlan id 40
$ ip link add name br1 type bridge
$ ip link set dev sw1p4.50 master br1
$ ip link set dev sw1p4.60 master br1
$ ip addr add 192.168.5.254/24 dev sw1p4.50
$ ip addr add 192.168.10.254/24 dev sw1p4.60
```
 2.  To that end, is it possible at all to create VLAN netdevs on VLAN unaware bridges? The documentation in the wiki for VLAN unaware bridges is quite sparse. Even if you can’t assign an address having the ability to create VLAN sub interfaces on regular bridges that still get offloaded to hardware could be quite beneficial.

**Comment by jmpolom** [comment]
@Mickey201 any further clarification available on this?

**Comment by Mickey201** [comment]
Hi @jmpolom,
I would like to conclude this issue.
Please refer to the last changes in the switchdev-prestera wiki pages.
We added more clarifications per your comments.

**Comment by jmpolom** [comment]
@Mickey201 I don't see any actual response/example to the specific [question](https://github.com/Marvell-switching/switchdev-prestera/issues/6#issuecomment-931795611) I asked above. Can you create a VLAN netdev on a bridge and assign it an IPv4 address?

This specific use case should be documented in the wiki but I do not seem to see it. If I have simply missed it, could you supply a link to the relevant section where it is described?

**Comment by jmpolom** [comment]
@Mickey201 I took a quick look through the wiki and didn't seem to find where the updated area is at? Was the [example](https://github.com/Marvell-switching/switchdev-prestera/issues/6#issuecomment-931597606) you wrote above specifically added in?

Basically I'm looking to see where the docs were updated to show how to create a VLAN netdev on the hardware accelerated bridge with an IPv4 address.

**Comment by Mickey201** [comment]
Hi @jmpolom, This is the updated page:
https://github.com/Marvell-switching/switchdev-prestera/wiki/bridge-and-vlan#vlan-unaware-configurations
Unfortunately, it is not clear to me what do you looking for and what tech information is still missing.
Per the link above, if you have specific parsing suggestions, please include them in the comments as I would like this issue to be closed ASAP.

**Comment by Mickey201** [comment]
With no further comments - I'm closing this case.
